# Generated by Django 5.1.1 on 2024-09-15 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BudgetData",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("designation", models.CharField(max_length=18)),
                ("department", models.CharField(max_length=11)),
                ("budget", models.IntegerField()),
                ("location", models.CharField(max_length=9)),
                (
                    "lastUpdated0",
                    models.CharField(default="Not Updated", max_length=12),
                ),
                ("lastUpdated1", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
