# Generated by Django 5.1.1 on 2024-09-15 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetdata",
            name="lastUpdated1",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
